initia-labs/initia-registry

README.md, _packages/initia-registry/package-lock.json, _packages/initia-registry/package.json, _packages/initia-registry/src/testnet/initia/chain.ts, _packages/initia-registry/src/testnet/minimove/chain.ts, _packages/initia-registry/src/testnet/miniwasm/assets.ts, _packages/initia-registry/src/testnet/miniwasm/chain.ts, devnets/initia/chain.json, devnets/stonemove/chain.json, devnets/stonewasm/chain.json, testnets/initia/chain.json, testnets/minimove/chain.json, testnets/miniwasm/chain.json
update provider from `Foundation` to `Initia Labs`
=> update provider from Foundation to Initia Labs

devnets/initia/assetlist.json
Update minitswap relate denoms due to restart change.
=> update: update minitswap relate asset denoms

devnets/initia/assetlist.json
Update name and description of devnet's minitswap relate tokens
=> update devnet minitswap name and description

chain.schema.json, testnets/initia/chain.json
* add authorizedUser field to chain schema
* add authorized-only APIs for skip
=> add authorized-only apis

testnets/milkyway/assetlist.json
This PR fixes the INIT display name for MilkyWay
=> fix: INIT display name for MilkyWay

testnets/blackwing/assetlist.json, testnets/civitia/assetlist.json, testnets/init_ai/assetlist.json, testnets/initia/assetlist.json, testnets/minimove/assetlist.json, testnets/miniwasm/assetlist.json, testnets/noon/assetlist.json, testnets/tucana/assetlist.json
Add milkINIT to each chain's asset list
=> feat: add milkinit to each chain

_packages/initia-registry/package.json, _packages/initia-registry/src/testnet/assets.ts, _packages/initia-registry/src/testnet/blackwing/assets.ts, _packages/initia-registry/src/testnet/chains.ts, _packages/initia-registry/src/testnet/civitia/assets.ts, _packages/initia-registry/src/testnet/index.ts, _packages/initia-registry/src/testnet/init_ai/assets.ts, _packages/initia-registry/src/testnet/initia/assets.ts, _packages/initia-registry/src/testnet/initia/chain.ts, _packages/initia-registry/src/testnet/milkyway/assets.ts, _packages/initia-registry/src/testnet/milkyway/chain.ts, _packages/initia-registry/src/testnet/milkyway/index.ts, _packages/initia-registry/src/testnet/minimove/assets.ts, _packages/initia-registry/src/testnet/minimove/chain.ts, _packages/initia-registry/src/testnet/miniwasm/assets.ts, _packages/initia-registry/src/testnet/miniwasm/chain.ts, _packages/initia-registry/src/testnet/noon/assets.ts, _packages/initia-registry/src/testnet/tucana/assets.ts, _packages/types/package.json, _packages/types/src/types/Chain.ts, _packages/types/src/zods/Chain.ts, chain.schema.json, devnets/stonemove/chain.json, devnets/stonewasm/chain.json, testnets/minimove/chain.json, testnets/miniwasm/chain.json
- Add executor api
- Update types package
- Update initia-registry package
=> feat: add executor api

testnets/blackwing/chain.json, testnets/civitia/chain.json, testnets/init_ai/chain.json, testnets/tucana/chain.json
Add executor apis for blackwing, civitia, init ai, and tucana
=> feat: add executor apis

testnets/noon/chain.json
=> add noon executor api

_packages/initia-registry/package.json, _packages/initia-registry/src/testnet/blackwing/assets.ts, _packages/initia-registry/src/testnet/blackwing/chain.ts, _packages/initia-registry/src/testnet/civitia/assets.ts, _packages/initia-registry/src/testnet/civitia/chain.ts, _packages/initia-registry/src/testnet/init_ai/assets.ts, _packages/initia-registry/src/testnet/init_ai/chain.ts, _packages/initia-registry/src/testnet/milkyway/assets.ts, _packages/initia-registry/src/testnet/milkyway/chain.ts, _packages/initia-registry/src/testnet/minimove/assets.ts, _packages/initia-registry/src/testnet/miniwasm/assets.ts, _packages/initia-registry/src/testnet/noon/assets.ts, _packages/initia-registry/src/testnet/noon/chain.ts, _packages/initia-registry/src/testnet/tucana/assets.ts, _packages/initia-registry/src/testnet/tucana/chain.ts
update initia registry package to 0.1.15
=> update initia registry package to 0.1.15

.github/workflows/utility/validate_data.py, .github/workflows/validate_data.yml, _packages/types/package.json, _packages/types/src/types/AssetList.ts, _packages/types/src/zods/AssetList.ts, assetlist.schema.json, testnets/blackwing/assetlist.json, testnets/civitia/assetlist.json, testnets/init_ai/assetlist.json, testnets/initia/assetlist.json, testnets/initia/chain.json, testnets/milkyway/assetlist.json, testnets/minimove/assetlist.json, testnets/miniwasm/assetlist.json, testnets/noon/assetlist.json, testnets/tucana/assetlist.json
- Add trace validation.
- Add traces for all op, ibc bridged asset.
=> Add denom traces and validation

testnets/initia/chain.json
Update mesa RPC/REST endpoint and fix polkachu's rest endpoint
=> update mesa rpc/rest endpoint

testnets/initia/chain.json, testnets/minimove/chain.json, testnets/miniwasm/chain.json
add `grpc://` for our grpc addresses
=> fix: specify grpc protocol

devnets/initia/chain.json, devnets/stonemove/chain.json, devnets/stonewasm/chain.json
=> update devnet to stone-17

testnets/initia/chain.json, testnets/minievm/chain.json, testnets/minimove/chain.json, testnets/miniwasm/chain.json
grpc-skip.testnet.initia.xyz is still setting up. So I kept non-postfixed one for now.
=> add skip-dedicated ones andupdate domain as testnet

testnets/initia/chain.json
i'll revert it after resolving rate limit
=> temporary use lcd instead of rest

testnets/initia/chain.json
add initiation-2 peer and persistence peer
=> feat: add initiation-2 peer and persistence peer

testnets/initia/chain.json
just simple update. i think we should fill more fields later
=> fix initia's codebase

testnets/minievm/chain.json, testnets/minimove/chain.json, testnets/miniwasm/chain.json
miniwasm-2 doesn't have upgrade proposal since there's no breaking changes
=> fix minitias' codabase

testnets/milkyway/chain.json
This PR adds Skip endpoints (RPC, gRPC and LCD).
=> chore: add Skip endpoints

testnets/minievm/chain.json, testnets/minimove/chain.json, testnets/miniwasm/chain.json
- add skip endpoints for minievm, miniwasm, minimove
=> feat: add skip endpoints

testnets/initia/chain.json
- update skip grpc endpoint for initia L1
=> fix grpc endpoint

chain.schema.json, testnets/milkyway/chain.json
make rest ,rpc and api endpoint start with `https://`
=> make rest ,rpc and api endpoint start with https://

testnets/civitia/chain.json
=> feat: add civitia grpc

testnets/minievm/chain.json
- fix gas denom on minievm-2 (umin -> GAS)
=> fix gas denom on minievm-2

_packages/types/package.json, _packages/types/src/types/Chain.ts, _packages/types/src/zods/Chain.ts
update `@initia/initia-registry-types` package as chain.schema.json changed
=> update initia registry types package

_packages/types/package.json, _packages/types/src/types/Chain.ts, _packages/types/src/zods/Chain.ts
update `@initia/initia-registry-types` to `0.0.22`
- add evm related fields
=> update type package to v0.0.22

testnets/civitia/chain.json
=> feat: add civitia executor uri

_packages/initia-registry/package-lock.json, _packages/initia-registry/package.json, _packages/initia-registry/src/testnet/civitia/chain.ts, _packages/initia-registry/src/testnet/milkyway/chain.ts, _packages/initia-registry/src/testnet/minievm/assets.ts, _packages/initia-registry/src/testnet/minievm/chain.ts
- update types version
- adjust civitia, minievm, milkyway chages
=> update: update initia-registry package to v0.2.2

testnets/miniwasm/assetlist.json, testnets/miniwasm/chain.json
Add op bridged usdc on miniwasm-2
=> feat: add op usdc on miniwasm

profiles/moo.json
=> add moo profile.json

mainnets/echelon/chain.json
set echelon gas price to 0.015uinit
=> update: set echelon gas price to 0.015uinit

.github/workflows/npm_pr_initia_registry.yml, testnets/initia/chain.json
- contents changed: remove outdated channels
- workflow changed: change initia-registry pr creation condition to release to prevent spam
=> remove outdated testnet channels
